config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  # == Pages
  root to: 'pages#home'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  # ==

  # == Blogs
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # ==

  # == Portfolios
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'
  get 'angular', to: 'portfolios#angular'
  # ==
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  has_many :technologies, :dependent => :delete_all
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: 600, width: 400)
    self.thumb_image ||= Placeholder.image_generator(height: 350, width: 200)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    if @portfolio_item.save
      flash[:notice] = "Success"
      redirect_to portfolios_path
    else
      flash[:alert] = "Failure"
      render new
    end
  end

  def edit

  end

  def show

  end

  def update
    if @portfolio_item.update(portfolio_params)
      flash[:notice] = "Success"
      redirect_to portfolios_path
    else
      flash[:alert] = "Failure"
      render new
    end
  end

  def destroy
    @portfolio_item.destroy
    flash[:notice] = "Portfolio item deleted successfully"
    redirect_to portfolios_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image, technologies_attributes: [:name] )
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with model: @portfolio_item, local: true do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <ul>
    <%= f.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="field">
    <%= f.label :main_image %>
    <%= f.text_field :main_image %>
  </div>

  <div class="field">
    <%= f.label :thumb_image %>
    <%= f.text_field :thumb_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/portfolios/_portfolio_item.html.erb
<h2><%= link_to(portfolio_item.title, portfolio_path(portfolio_item)) %></h2>

<p><%= portfolio_item.subtitle %></p>
<p><%= portfolio_item.body %></p>
<p><%= image_tag(portfolio_item.thumb_image) %></p>
<%= link_to("Edit", edit_portfolio_path(portfolio_item)) if logged_in?(:site_admin) %>
<%= link_to("Show", show_portfolio_path(portfolio_item)) %>
<%= link_to("Delete", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure?" }) if logged_in?(:site_admin) %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to("New Portfolio Item", new_portfolio_path) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <h2><%= link_to(portfolio_item.title, portfolio_path(portfolio_item)) %></h2>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <p><%= image_tag(portfolio_item.thumb_image) %></p>
  <%= link_to("Edit", edit_portfolio_path(portfolio_item)) if logged_in?(:site_admin) %>
  <%= link_to("Show", show_portfolio_path(portfolio_item)) %>
  <%= link_to("Delete", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure?" }) if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this portfolio item</h1>

<%= render partial: "portfolios/form" %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to("New Portfolio Item", new_portfolio_path) if logged_in?(:site_admin) %>

<%= render partial: "portfolio_item", collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>New portfolio item</h1>

<%= render partial: "portfolios/form" %>

app/views/portfolios/show.html.erb
<h1>Show Portfolio item</h1>

<p><%= image_tag(@portfolio_item.main_image) %></p>
<h2><%= @portfolio_item.title %></h2>
<p><%= @portfolio_item.subtitle %></p>
<p><%= @portfolio_item.body %></p>

<h2>Technologies used:</h2>
<% @portfolio_item.technologies.each do |t| %>
  <p><%= t.name %></p>
<% end %>

<%= link_to("Edit", edit_portfolio_path(@portfolio_item)) if logged_in?(:site_admin) %>