config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  # == Pages
  root to: 'pages#home'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  # ==

  # == Blogs
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # ==

  # == Portfolios
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'
  get 'angular', to: 'portfolios#angular'
  # ==
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :body, :title

  belongs_to :topic, optional: true

end

app/models/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :first_name, :last_name, :email
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  has_many :technologies, :dependent => :delete_all
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: 600, width: 400)
    self.thumb_image ||= Placeholder.image_generator(height: 350, width: 200)
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: 250, width: 250)
  end

end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                          ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include CurrentUserConcern
  include DeviseWhitelistConcern
  include SetSourceConcern
  include DefaultPageContentConcern
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  def index
    @blogs = Blog.all
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
    end
    flash[:notice] = "Status Updated"
    redirect_to blogs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}/#{SecureRandom.hex(3)}/000000"
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    if @portfolio_item.save
      flash[:notice] = "Success"
      redirect_to portfolios_path
    else
      flash[:alert] = "Failure"
      render new
    end
  end

  def edit

  end

  def show

  end

  def update
    if @portfolio_item.update(portfolio_params)
      flash[:notice] = "Success"
      redirect_to portfolios_path
    else
      flash[:alert] = "Failure"
      render new
    end
  end

  def destroy
    @portfolio_item.destroy
    flash[:notice] = "Portfolio item deleted successfully"
    redirect_to portfolios_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image, technologies_attributes: [:name] )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def login_helper(style = "")
    unless current_user.is_a?(GuestUser)
      link_to("Logout", destroy_user_session_path, method: :delete, class: style)
    else
      (link_to("Register", new_user_registration_path, class: style)) +
      (" ".html_safe) +
      (link_to("Login", new_user_session_path, class: style))
    end
  end

  def source_helper
    if session[:source]
      greeting = "Thank you for visiting me from #{ session[:source]}"
      content_tag(:p, greeting, class: "source-greeting" )
    end
  end

  def copyright_generator
    @copyright = DyllanCullingworthViewTool::Renderer.copyright 'Dyllan Cullingworth', 'All rights reserved'
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">

          <%= render partial: "shared/application_nav" %>
          <%= render partial: "shared/flash" %>

          <%= yield %>
          <%= source_helper %>
          <%= render partial: "shared/application_footer" %>

        </div>
      </div>
    </div>

  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title><%= @page_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>
<body>

  <%#= render partial: "blogs/featured" %>

  <div class="nav_container">
    <%= render partial: "shared/application_nav" %>
  </div>

  <div class="container">

    <div class="py-4 my-4 border-bottom">
      <h1>My Blog</h1>
      <p class="text-muted">A place for me to share my stories</p>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </div>

    <%= render partial: "blogs/blog_nav" %>

    <main role="main">
      <div class="row">

        <div class="col-md-9 blog-main">

          <%= yield %>

        </div>

        <aside class="col-md-3 blog-sidebar">

          <%= render partial: "blogs/sidebar" %>

        </aside>

      </div><!-- /.row -->
    </main>
    <%= source_helper %>
  </div>

  <%= render partial: "blogs/footer" %>

</body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

  <%= render partial: "shared/nav" %>
  <%= render partial: "shared/flash" %>
  <%= login_helper %>
  <%= yield %>
  <%= source_helper %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About me</h1>
<br>
<p>I am an aspiring Ruby on Rails full stack developer, I touched my first piece of code in March 2020, and I fell in love with it right away.
  My goal is to create beautiful and functional products that clients and users love.</p>
<p>I believe that being open is the best way to do business, that is why I communicate with my clients through every step of the process to ensure I produce what they want, not what I think they want.</p>

app/views/pages/contact.html.erb
<h1>Want to work together?</h1>




<div class="row">
  <div class="col-md-6">
    <h3>Office Address</h3>
    <p>107 Rio Street, Rexford, Knysna, 6571</p>
    <h3>Phone</h3>
    <p> <%= number_to_phone "0713834285" %></p>
    <h3>Email</h3>
    <p> <a href="mailto:mmdyllan@gmail.com?subject=PortfolioContant">Email me</a></p>
  </div>
  <div class="col-md-6">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3306.7077755270343!2d23.042441014848865!3d-34.025711234650416!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1e78ea81525bdcd5%3A0x7613e871a19d481b!2s107%20Rio%20St%2C%20Rexford%2C%20Knysna%2C%206571!5e0!3m2!1sen!2sza!4v1612364650956!5m2!1sen!2sza"
            width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
    </iframe>
  </div>
</div>

app/views/pages/home.html.erb
<div class="inner cover">
  <h1 class="cover-heading">Welcome.</h1>
  <br>
  <p class="lead">If you want something done the way you want it done, not the way someone else thinks you want it done, look no further. I will be with you every step of the way as we bring your vision to life.</p>
  <p class="lead">
    <%= link_to "About Me", about_path, class: "btn btn-lg btn-secondary" %>
  </p>
</div>

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Dyllan Cullingworth</h3>
    <nav class="nav nav-masthead">
      <%= link_to "Home", root_path, class: "nav-link" %>
      <%= link_to "About", about_path, class: "nav-link" %>
      <%= link_to "Contact", contact_path, class: "nav-link" %>
      <%= link_to "Blog", blogs_path, class: "nav-link" %>
      <%= link_to "Portfolios", portfolios_path, class: "nav-link" %>
      <%= login_helper("nav-link") %>
    </nav>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="flash">
  <% if flash %>
    <div class="flash_message">
      <% if flash[:notice] %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-warning">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<div class="nav_links">

</div>